from pathlib import Path
p=Path(__file__).with_name('aplicar_ampliacion_gas.py')
s=p.read_text(encoding='utf-8')
s=s.replace("if len(regs)!=75: raise SystemExit(f'Esperados 75, obtenidos {len(regs)}')","K=len(regs); NV=15; NC=K-NV")
s=s.replace("if totals!=(1679,3142,1245,416): raise SystemExit('Totales: '+str(totals))","esperados=(1604+K,3067+K,1230+NV,356+NC)\n if totals!=esperados: raise SystemExit('Totales: '+str(totals)+' esperados '+str(esperados))")
s=s.replace("if len(base.parametros) < 1679:","if len(base.parametros) < {1604+K}:")
s=s.replace("por lo menos 1679 parámetros revisados","por lo menos {1604+K} parámetros revisados")
s=s.replace("if validados < 1245:","if validados < {1230+NV}:")
s=s.replace("al menos 1245 numerales RNE validados","al menos {1230+NV} numerales RNE validados")
s=s.replace("if criterios < 416:","if criterios < {356+NC}:")
s=s.replace("al menos 416 criterios técnicos revisados","al menos {356+NC} criterios técnicos revisados")
s=s.replace("if len(todas) < 3142:","if len(todas) < {3067+K}:")
s=s.replace("por lo menos 3142 preguntas técnicas","por lo menos {3067+K} preguntas técnicas")
s=s.replace("s=C.read_text(encoding='utf-8'); s=rep(s,'if len(base.parametros) < 1604:','if len(base.parametros) < {1604+K}:')","s=C.read_text(encoding='utf-8'); s=rep(s,'if len(base.parametros) < 1604:',f'if len(base.parametros) < {1604+K}:')")
s=s.replace("s=rep(s,'por lo menos 1604 parámetros revisados','por lo menos {1604+K} parámetros revisados')","s=rep(s,'por lo menos 1604 parámetros revisados',f'por lo menos {1604+K} parámetros revisados')")
s=s.replace("s=rep(s,'if validados < 1230:','if validados < {1230+NV}:')","s=rep(s,'if validados < 1230:',f'if validados < {1230+NV}:')")
s=s.replace("s=rep(s,'al menos 1230 numerales RNE validados','al menos {1230+NV} numerales RNE validados')","s=rep(s,'al menos 1230 numerales RNE validados',f'al menos {1230+NV} numerales RNE validados')")
s=s.replace("s=rep(s,'if criterios < 356:','if criterios < {356+NC}:')","s=rep(s,'if criterios < 356:',f'if criterios < {356+NC}:')")
s=s.replace("s=rep(s,'al menos 356 criterios técnicos revisados','al menos {356+NC} criterios técnicos revisados')","s=rep(s,'al menos 356 criterios técnicos revisados',f'al menos {356+NC} criterios técnicos revisados')")
s=s.replace("s=rep(s,'if len(todas) < 3067:','if len(todas) < {3067+K}:')","s=rep(s,'if len(todas) < 3067:',f'if len(todas) < {3067+K}:')")
s=s.replace("s=rep(s,'por lo menos 3067 preguntas técnicas','por lo menos {3067+K} preguntas técnicas')","s=rep(s,'por lo menos 3067 preguntas técnicas',f'por lo menos {3067+K} preguntas técnicas')")
s=s.replace("Se incorporaron **75 parámetros** y **75 preguntas**","Se incorporaron **{K} parámetros** y **{K} preguntas**")
s=s.replace("- Parámetros totales: `1679`.","- Parámetros totales: `{1604+K}`.")
s=s.replace("- Registros `validado_con_numeral`: `1245`.","- Registros `validado_con_numeral`: `{1230+NV}`.")
s=s.replace("- Criterios técnicos revisados: `416`.","- Criterios técnicos revisados: `{356+NC}`.")
s=s.replace("- Preguntas técnicas: `3142`.","- Preguntas técnicas: `{3067+K}`.")
s=s.replace("print('Aplicados 75 parámetros y preguntas; versión 2.7.0')","print(f'Aplicados {K} parámetros y preguntas; versión 2.7.0')")
p.write_text(s,encoding='utf-8')
print('Conteos de gas convertidos a dinámicos')
