from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NORM_PATH = ROOT / "backend" / "normativa_tecnica.json"
FAQ_PATH = ROOT / "backend" / "preguntas_tecnicas.json"
CHECK_PATH = ROOT / "scripts" / "check_normativa.py"
DOC_PATH = ROOT / "docs" / "VALIDACION_NORMATIVA_PROCESOS_2026-07-27.md"

norm = json.loads(NORM_PATH.read_text(encoding="utf-8"))
faq = json.loads(FAQ_PATH.read_text(encoding="utf-8"))

if norm.get("version") != "1.4.0" or len(norm.get("parametros", [])) != 100:
    raise SystemExit("La base cambió desde la versión 1.4.0; revisar antes de aplicar.")

existing_ids = {item["id"] for item in norm["parametros"]}
existing_qids = {
    item.get("id")
    for category in faq.get("categorias", [])
    for item in category.get("preguntas", [])
    if isinstance(item, dict)
}
category_map = {
    category.get("nombre") or category.get("categoria"): category
    for category in faq.get("categorias", [])
}

RNE_URL = "https://www.gob.pe/institucion/vivienda/informes-publicaciones/2309793-reglamento-nacional-de-edificaciones-rne"
REVIEW_DATE = "2026-07-27"

STANDARD_INFO = {
    "E.060": ("Concreto Armado", "DS N.° 010-2009-VIVIENDA"),
    "E.070": ("Albañilería", "DS N.° 011-2006-VIVIENDA"),
    "G.050": ("Seguridad durante la Construcción", "DS N.° 010-2009-VIVIENDA"),
    "GE.030": ("Calidad de la Construcción", "DS N.° 011-2006-VIVIENDA"),
}


def source(standard: str, numeral: str) -> dict:
    title, device = STANDARD_INFO[standard]
    return {
        "tipo": "RNE",
        "norma": standard,
        "denominacion": title,
        "dispositivo": device,
        "numeral": numeral,
        "numeral_confirmado": True,
        "url_oficial": RNE_URL,
    }


def text_value(text: str) -> dict:
    return {"tipo": "texto", "texto": text}


def number_value(value: float | int, unit: str, text: str) -> dict:
    return {"tipo": "numero", "valor": value, "unidad": unit, "texto": text}


def formula_value(formula: str, text: str) -> dict:
    return {"tipo": "formula", "formula": formula, "texto": text}


new_parameters: list[dict] = []
new_questions: list[tuple[str, dict]] = []
next_question = 1570


def add(
    *,
    parameter_id: str,
    category: str,
    element: str,
    parameter: str,
    classification: str,
    value: dict,
    standard: str,
    numeral: str,
    conditions: list[str],
    warning: str,
    faq_category: str,
    question: str,
    answer: str,
) -> None:
    global next_question
    if parameter_id in existing_ids or any(item["id"] == parameter_id for item in new_parameters):
        raise SystemExit(f"Identificador normativo duplicado: {parameter_id}")
    if faq_category not in category_map:
        raise SystemExit(f"Categoría FAQ inexistente: {faq_category}")
    question_id = f"q{next_question}"
    next_question += 1
    if question_id in existing_qids:
        raise SystemExit(f"Pregunta duplicada: {question_id}")
    new_parameters.append(
        {
            "id": parameter_id,
            "categoria": category,
            "elemento": element,
            "parametro": parameter,
            "clasificacion": classification,
            "valor": value,
            "condiciones": conditions,
            "fuente": source(standard, numeral),
            "estado_revision": "validado_con_numeral",
            "advertencia": warning,
            "faq_relacionadas": [question_id],
            "fecha_revision": REVIEW_DATE,
        }
    )
    new_questions.append(
        (faq_category, {"id": question_id, "pregunta": question, "respuesta": answer})
    )


# E.060: mezclado, transporte y colocación del concreto.
add(parameter_id="e060-medicion-materiales-proporciones", category="Procesos de concreto", element="Dosificación en obra", parameter="Medición de materiales", classification="condicion_normativa", value=text_value("Los materiales deben medirse por medios que garanticen las proporciones especificadas."), standard="E.060", numeral="5.8.1", conditions=["La dosificación debe corresponder a la mezcla aprobada y a la resistencia especificada."], warning="Medir cemento, arena, piedra o agua con recipientes variables impide controlar la mezcla.", faq_category="Concreto en Viviendas de Albañilería", question="¿Se pueden medir los materiales del concreto al cálculo o por paladas?", answer="No. La E.060 exige medios que garanticen las proporciones especificadas; los recipientes y la dosificación deben ser controlables y repetibles.")
add(parameter_id="e060-mezclado-uniforme-descarga-completa", category="Procesos de concreto", element="Mezcladora de concreto", parameter="Uniformidad y descarga", classification="condicion_normativa", value=text_value("El concreto debe mezclarse hasta lograr distribución uniforme y la mezcladora debe descargarse completamente antes de volver a cargarla."), standard="E.060", numeral="5.8.2", conditions=["La descarga no debe dejar material de una tanda mezclándose con la siguiente."], warning="Cargar nuevamente una mezcladora con restos altera la dosificación y uniformidad.", faq_category="Concreto en Viviendas de Albañilería", question="¿Puedo cargar otra tanda sin vaciar completamente la mezcladora?", answer="No. La E.060 exige descargarla completamente y lograr una mezcla uniforme antes de usar el concreto.")
add(parameter_id="e060-mezclado-tiempo-minimo", category="Procesos de concreto", element="Concreto preparado en obra", parameter="Tiempo de mezclado", classification="minimo_normativo", value=number_value(90, "s", "El mezclado debe durar por lo menos 90 segundos después de ingresar todos los materiales, salvo que ensayos de uniformidad demuestren que un tiempo menor es satisfactorio."), standard="E.060", numeral="5.8.4(d)", conditions=["El tiempo se cuenta después de que todos los materiales estén dentro del tambor.", "La excepción requiere ensayos de uniformidad, no apreciación visual."], warning="Contar desde que empieza a cargarse la mezcladora reduce el tiempo efectivo de mezclado.", faq_category="Concreto en Viviendas de Albañilería", question="¿Cuánto tiempo mínimo debe mezclarse el concreto preparado en obra?", answer="Por regla general, al menos 90 segundos después de que todos los materiales estén dentro del tambor; un tiempo menor requiere demostración mediante ensayos de uniformidad.")
add(parameter_id="e060-mezclado-registro-tandas", category="Control de calidad del concreto", element="Concreto preparado en obra", parameter="Registro de producción", classification="condicion_normativa", value=text_value("Debe registrarse el número de tandas, dosificación, ubicación final, hora y fecha del mezclado y colocación."), standard="E.060", numeral="5.8.4(f)", conditions=["El registro debe permitir relacionar cada tanda con el elemento construido."], warning="Sin identificación no puede investigarse una tanda defectuosa ni relacionarse con sus ensayos.", faq_category="Compra de Materiales y Control de Calidad", question="¿Qué datos deben anotarse de cada tanda de concreto preparada en obra?", answer="Número de tanda, dosificación, lugar donde se colocó, fecha y hora del mezclado y de la colocación.")
add(parameter_id="e060-transporte-evitar-segregacion-perdida", category="Procesos de concreto", element="Transporte del concreto", parameter="Protección de la mezcla", classification="condicion_normativa", value=text_value("El transporte debe evitar segregación y pérdida de material."), standard="E.060", numeral="5.9.1", conditions=["El método debe conservar la uniformidad desde la mezcladora hasta la ubicación final."], warning="Recorridos largos, carretillas con fugas o descargas bruscas separan la piedra de la pasta.", faq_category="Concreto en Viviendas de Albañilería", question="¿Qué debe evitarse al transportar concreto desde la mezcladora?", answer="Debe evitarse la segregación y la pérdida de material durante todo el recorrido hasta el punto de colocación.")
add(parameter_id="e060-transporte-sin-interrupciones", category="Procesos de concreto", element="Abastecimiento de concreto", parameter="Continuidad del suministro", classification="condicion_normativa", value=text_value("El equipo debe abastecer sin segregación ni interrupciones que causen pérdida de plasticidad entre capas sucesivas."), standard="E.060", numeral="5.9.2", conditions=["La capacidad de transporte debe ser compatible con el ritmo de colocación."], warning="Una espera prolongada entre capas puede originar juntas no previstas.", faq_category="Concreto en Viviendas de Albañilería", question="¿Por qué debe planificarse el ritmo de transporte del concreto?", answer="Porque la E.060 exige un suministro sin interrupciones que provoquen pérdida de plasticidad entre capas sucesivas.")
add(parameter_id="e060-colocacion-cerca-ubicacion-final", category="Procesos de concreto", element="Colocación del concreto", parameter="Punto de descarga", classification="condicion_normativa", value=text_value("El concreto debe depositarse lo más cerca posible de su ubicación final."), standard="E.060", numeral="5.10.1", conditions=["Debe minimizarse el desplazamiento posterior dentro del encofrado."], warning="Arrastrar la mezcla grandes distancias favorece segregación y vacíos.", faq_category="Concreto en Viviendas de Albañilería", question="¿Se puede descargar el concreto en un extremo y empujarlo por todo el encofrado?", answer="No es el procedimiento correcto. Debe depositarse lo más cerca posible de su posición final para evitar segregación.")
add(parameter_id="e060-colocacion-plastica-continua", category="Procesos de concreto", element="Vaciado de concreto", parameter="Continuidad y estado plástico", classification="condicion_normativa", value=text_value("La colocación debe mantener el concreto plástico y ejecutarse continuamente o en capas que no formen juntas dentro de la sección."), standard="E.060", numeral="5.10.2 y 5.10.5", conditions=["El tramo o paño debe completarse hasta sus límites o juntas predeterminadas."], warning="Reanudar sobre una capa ya endurecida genera una junta fría no prevista.", faq_category="Concreto en Viviendas de Albañilería", question="¿Se puede interrumpir varias horas el vaciado de una columna o viga?", answer="No debe improvisarse. La colocación debe ser continua hasta completar el tramo o llegar a una junta previamente definida.")
add(parameter_id="e060-concreto-endurecido-contaminado-prohibido", category="Procesos de concreto", element="Concreto fresco", parameter="Condición para colocación", classification="prohibicion", value=text_value("No debe colocarse concreto parcialmente endurecido o contaminado con materiales extraños."), standard="E.060", numeral="5.10.3", conditions=["La mezcla debe conservar las condiciones aprobadas antes de ingresar a la estructura."], warning="Agregar agua o mezclarlo con material nuevo no corrige un concreto que ya empezó a endurecer.", faq_category="Concreto en Viviendas de Albañilería", question="¿Puedo usar concreto que ya comenzó a endurecer en la carretilla?", answer="No. La E.060 prohíbe colocar concreto parcialmente endurecido o contaminado.")
add(parameter_id="e060-adicion-agua-postmezclado-prohibida", category="Procesos de concreto", element="Concreto ya preparado", parameter="Adición posterior de agua", classification="prohibicion", value=text_value("No debe añadirse agua al concreto después de preparado ni remezclarse después del fraguado inicial, salvo aprobación de la supervisión."), standard="E.060", numeral="5.10.4", conditions=["Cualquier ajuste autorizado debe estar controlado y documentado."], warning="El agua añadida sin control reduce resistencia y durabilidad y aumenta fisuración.", faq_category="Concreto en Viviendas de Albañilería", question="¿Puedo echar agua al concreto porque se puso duro durante el vaciado?", answer="No sin aprobación y control de la supervisión. La E.060 prohíbe agregar agua después de preparado o remezclarlo después del fraguado inicial.")
add(parameter_id="e060-compactacion-alrededor-refuerzo", category="Procesos de concreto", element="Consolidación del concreto", parameter="Llenado de espacios", classification="condicion_normativa", value=text_value("El concreto debe compactarse cuidadosamente alrededor del refuerzo, elementos embebidos y esquinas del encofrado."), standard="E.060", numeral="5.10.7", conditions=["La compactación debe evitar vacíos sin causar segregación."], warning="Los cangrejeros alrededor del acero reducen adherencia, recubrimiento y durabilidad.", faq_category="Concreto en Viviendas de Albañilería", question="¿Qué zonas necesitan especial cuidado durante el vibrado?", answer="Alrededor del acero, pases y elementos embebidos, así como en las esquinas del encofrado.")
add(parameter_id="e060-vibrador-no-desplaza-concreto", category="Procesos de concreto", element="Vibrador de concreto", parameter="Uso permitido", classification="prohibicion", value=text_value("El vibrador no debe utilizarse para desplazar lateralmente el concreto dentro del encofrado."), standard="E.060", numeral="5.10.7", conditions=["La mezcla debe descargarse cerca de su posición final."], warning="Usar el vibrador como herramienta de empuje produce segregación y zonas con exceso de pasta.", faq_category="Concreto en Viviendas de Albañilería", question="¿Puedo usar el vibrador para empujar el concreto a otra zona?", answer="No. La E.060 prohíbe usarlo para desplazar lateralmente la mezcla dentro del encofrado.")
add(parameter_id="e060-lluvia-vaciado-sin-proteccion-prohibido", category="Procesos de concreto", element="Vaciado durante lluvia", parameter="Condición de colocación", classification="prohibicion", value=text_value("No debe colocarse concreto durante lluvia, nevada o granizada sin métodos de protección autorizados."), standard="E.060", numeral="5.11.1", conditions=["El agua de lluvia no puede aumentar el agua de mezcla ni dañar el acabado."], warning="Cubrir después del vaciado no corrige una mezcla ya alterada por lluvia.", faq_category="Concreto en Viviendas de Albañilería", question="¿Se puede vaciar concreto mientras llueve?", answer="Solo con protección adecuada autorizada. La lluvia no debe aumentar el agua de mezcla ni dañar la superficie.")
add(parameter_id="e060-concreto-temperatura-colocacion-maxima", category="Procesos de concreto", element="Concreto al colocarse", parameter="Temperatura máxima", classification="maximo_normativo", value=number_value(32, "°C", "La temperatura del concreto al colocarse no debe superar 32 °C."), standard="E.060", numeral="5.11.2", conditions=["También debe evitarse pérdida de asentamiento, fragua instantánea y juntas frías."], warning="No basta medir la temperatura ambiental; debe controlarse la mezcla.", faq_category="Concreto en Viviendas de Albañilería", question="¿Cuál es la temperatura máxima del concreto al momento de colocarlo?", answer="La E.060 establece un máximo de 32 °C y exige evitar pérdida de asentamiento, fragua instantánea y juntas frías.")
add(parameter_id="e060-encofrado-acero-temperatura-maxima", category="Procesos de concreto", element="Encofrado metálico y acero", parameter="Temperatura máxima antes del vaciado", classification="maximo_normativo", value=number_value(50, "°C", "La temperatura de los encofrados metálicos y del acero de refuerzo no debe superar 50 °C."), standard="E.060", numeral="5.11.4", conditions=["Debe controlarse especialmente bajo exposición solar intensa."], warning="El acero o molde recalentado acelera la pérdida de agua y afecta el concreto de contacto.", faq_category="Concreto en Viviendas de Albañilería", question="¿Se puede vaciar sobre acero o encofrado metálico muy caliente?", answer="No si supera 50 °C. Debe enfriarse y verificarse antes de colocar el concreto.")
add(parameter_id="e060-clima-frio-umbral", category="Procesos de concreto", element="Vaciado en clima frío", parameter="Umbral de aplicación", classification="maximo_normativo", value=number_value(5, "°C", "Se considera clima frío cuando durante el vaciado la temperatura ambiente puede estar por debajo de 5 °C."), standard="E.060", numeral="5.12.1", conditions=["Al alcanzarse este supuesto se aplican las medidas adicionales del numeral 5.12."], warning="No debe continuarse con procedimientos ordinarios si existe riesgo de congelamiento.", faq_category="Concreto en Viviendas de Albañilería", question="¿Desde qué temperatura la E.060 considera que el vaciado se realiza en clima frío?", answer="Cuando en cualquier momento del vaciado la temperatura ambiente puede bajar de 5 °C.")
add(parameter_id="e060-clima-frio-curado-temperatura-minima", category="Procesos de concreto", element="Concreto colocado en clima frío", parameter="Temperatura durante el curado", classification="minimo_normativo", value=number_value(10, "°C", "Cuando el ambiente es menor de 5 °C, el concreto colocado debe mantenerse por encima de 10 °C durante el curado."), standard="E.060", numeral="5.12.3", conditions=["La protección debe evitar daños por concentración de calor."], warning="Calentar sin control también puede fisurar o carbonatar tempranamente el concreto.", faq_category="Concreto en Viviendas de Albañilería", question="¿Qué temperatura debe conservar el concreto durante el curado en clima frío?", answer="Si el ambiente está por debajo de 5 °C, debe mantenerse el concreto sobre 10 °C durante el período de curado.")

# E.060: encofrados, apuntalamiento, instalaciones embebidas y juntas.
add(parameter_id="e060-encofrado-hermeticidad", category="Encofrados y apuntalamiento", element="Encofrado", parameter="Hermeticidad", classification="condicion_normativa", value=text_value("El encofrado debe ser suficientemente hermético para impedir la fuga de mortero."), standard="E.060", numeral="6.1.2", conditions=["Las juntas y uniones deben cerrarse antes del vaciado."], warning="La fuga de pasta genera cangrejeras y reduce la sección efectiva.", faq_category="Seguridad en la Autoconstrucción", question="¿Por qué el encofrado debe ser hermético?", answer="Para impedir la fuga de mortero; las aberturas producen pérdida de pasta, cangrejeras y acabado defectuoso.")
add(parameter_id="e060-encofrado-arriostramiento", category="Encofrados y apuntalamiento", element="Encofrado", parameter="Arriostramiento y amarre", classification="condicion_normativa", value=text_value("El encofrado debe estar arriostrado o amarrado para conservar su posición y forma."), standard="E.060", numeral="6.1.3", conditions=["Debe resistir el empuje, vibrado, personal y cargas de construcción."], warning="Un molde aparentemente firme puede abrirse o volcar durante el llenado.", faq_category="Seguridad en la Autoconstrucción", question="¿Qué evita que un encofrado se abra o se mueva durante el vaciado?", answer="El diseño, los amarres y arriostres adecuados; la E.060 exige que conserve su posición y forma.")
add(parameter_id="e060-encofrado-cargas-diseno", category="Encofrados y apuntalamiento", element="Diseño de encofrado", parameter="Cargas y velocidad de colocación", classification="condicion_normativa", value=text_value("El diseño debe considerar velocidad y método de colocación, cargas de construcción e impacto."), standard="E.060", numeral="6.1.5", conditions=["Las cargas incluyen concreto fresco, trabajadores, equipos, almacenamiento e impacto."], warning="Copiar la separación de puntales de otra obra no demuestra capacidad.", faq_category="Seguridad en la Autoconstrucción", question="¿Qué cargas deben considerarse al diseñar un encofrado?", answer="El concreto fresco, el método y velocidad de vaciado, trabajadores, equipos, materiales e impactos de construcción.")
add(parameter_id="e060-desencofrado-sin-plazo-universal", category="Encofrados y apuntalamiento", element="Desencofrado", parameter="Momento de retiro", classification="depende_calculo", value=text_value("No existe un plazo universal: debe existir resistencia suficiente para evitar daño y deben considerarse cargas y deflexiones."), standard="E.060", numeral="6.2.1", conditions=["La decisión debe basarse en resistencia real, elemento, luz, cargas, clima y sistema de apoyo."], warning="Retirar por costumbre a un número fijo de días puede causar deformación permanente o colapso.", faq_category="Losas, Techos y Diafragmas", question="¿La E.060 fija un número único de días para desencofrar?", answer="No. Exige verificar resistencia suficiente, cargas de construcción y posibles deflexiones antes de retirar el encofrado.")
add(parameter_id="e060-apuntalamiento-programacion-previa", category="Encofrados y apuntalamiento", element="Puntales y reapuntalamiento", parameter="Procedimiento y programación", classification="condicion_normativa", value=text_value("Antes de construir debe definirse el procedimiento y programa de retiro de puntales, reapuntalamiento y transferencia de cargas."), standard="E.060", numeral="6.2.2.1", conditions=["Debe sustentarse mediante análisis y resistencia del concreto cuando la supervisión lo requiera."], warning="Improvisar el retiro piso por piso puede sobrecargar losas jóvenes.", faq_category="Losas, Techos y Diafragmas", question="¿Cuándo debe planificarse el retiro y reapuntalamiento de una losa?", answer="Antes del inicio de la construcción, considerando la transferencia de cargas y la resistencia que alcanzará cada nivel.")
add(parameter_id="e060-estructura-sin-puntales-carga-maxima", category="Encofrados y apuntalamiento", element="Estructura sin apuntalamiento", parameter="Carga de construcción", classification="maximo_normativo", value=text_value("No deben aplicarse cargas que excedan la suma de cargas muertas y vivas de diseño, salvo análisis que demuestre resistencia suficiente."), standard="E.060", numeral="6.2.2.2", conditions=["El almacenamiento de ladrillos, cemento o equipos sobre una losa joven cuenta como carga de construcción."], warning="Acopiar materiales en un punto puede superar localmente la capacidad aunque el peso total parezca reducido.", faq_category="Losas, Techos y Diafragmas", question="¿Puedo almacenar ladrillos y cemento sobre una losa recién desapuntalada?", answer="Solo si las cargas no exceden las consideradas en diseño o un análisis demuestra capacidad suficiente; la losa joven puede deformarse o fallar.")
add(parameter_id="e060-tuberia-aluminio-proteccion", category="Instalaciones embebidas", element="Tubería o ducto de aluminio", parameter="Protección en concreto estructural", classification="prohibicion", value=text_value("No debe embeberse aluminio sin recubrimiento o pintura adecuada contra la reacción concreto-aluminio y la acción electrolítica."), standard="E.060", numeral="6.3.2", conditions=["La protección debe ser compatible con el concreto y el acero."], warning="El contacto directo puede producir reacción, corrosión y daño interno.", faq_category="Instalaciones Eléctricas en Viviendas", question="¿Se puede dejar un ducto de aluminio directamente embebido en concreto estructural?", answer="No sin protección adecuada contra la reacción con el concreto y la acción electrolítica con el acero.")
add(parameter_id="e060-columna-tuberias-area-maxima", category="Instalaciones embebidas", element="Tuberías embebidas en columna", parameter="Área ocupada", classification="maximo_normativo", value=number_value(4, "% del área de la sección", "Las tuberías, ductos y conexiones embebidos en una columna no deben ocupar más de 4% del área usada para calcular su resistencia o protección contra fuego."), standard="E.060", numeral="6.3.4", conditions=["La ubicación debe estar aprobada y no debilitar significativamente el elemento."], warning="El 4% no autoriza a cortar acero ni a concentrar varios ductos en una cara.", faq_category="Instalaciones Eléctricas en Viviendas", question="¿Qué área máxima pueden ocupar los ductos embebidos en una columna?", answer="Como máximo 4% del área de la sección utilizada para calcular su resistencia o protección contra incendio, y sin afectar el acero.")
add(parameter_id="e060-tuberia-dimension-exterior-maxima", category="Instalaciones embebidas", element="Tubería embebida en losa, muro o viga", parameter="Dimensión exterior", classification="formula_normativa", value=formula_value("dimensión exterior ≤ espesor del elemento / 3", "Sin aprobación específica del ingeniero estructural, la dimensión exterior no debe superar un tercio del espesor de la losa, muro o viga."), standard="E.060", numeral="6.3.5(a)", conditions=["Aplica a tuberías embebidas, no a pases aislados que solo atraviesan el elemento."], warning="Cumplir un tercio no reemplaza revisar resistencia, recubrimientos y separación del acero.", faq_category="Instalaciones Sanitarias en Viviendas", question="¿Qué diámetro máximo puede tener una tubería embebida en una losa, muro o viga?", answer="Sin aprobación del estructural, su dimensión exterior no debe superar un tercio del espesor total del elemento.")
add(parameter_id="e060-tuberias-separacion-minima", category="Instalaciones embebidas", element="Tuberías o ductos embebidos", parameter="Separación entre ejes", classification="formula_normativa", value=formula_value("s ≥ 3D", "Las tuberías o ductos deben separarse al menos tres veces su diámetro o ancho, medido de centro a centro."), standard="E.060", numeral="6.3.5(b)", conditions=["Aplica cuando los planos no hayan sido específicamente aprobados por el ingeniero estructural."], warning="Agrupar ductos crea una franja débil y dificulta el vaciado.", faq_category="Instalaciones Sanitarias en Viviendas", question="¿Qué separación mínima debe haber entre tuberías embebidas en concreto?", answer="Al menos tres veces su diámetro o ancho, medida entre ejes, salvo detalle aprobado por el ingeniero estructural.")
add(parameter_id="e060-tuberia-recubrimiento-minimo", category="Instalaciones embebidas", element="Tubería embebida en concreto", parameter="Recubrimiento", classification="condicion_normativa", value=text_value("Recubrimiento mínimo: 40 mm en superficies expuestas a intemperie o suelo y 20 mm en superficies no expuestas."), standard="E.060", numeral="6.3.10", conditions=["El recubrimiento se mide desde la superficie exterior de la tubería o conexión."], warning="Estos recubrimientos no sustituyen los exigidos para el acero ni autorizan interferencias.", faq_category="Instalaciones Sanitarias en Viviendas", question="¿Qué recubrimiento necesita una tubería embebida en concreto?", answer="40 mm si la superficie está expuesta a intemperie o suelo y 20 mm en superficies no expuestas directamente.")
add(parameter_id="e060-tuberia-refuerzo-transversal-minimo", category="Instalaciones embebidas", element="Zona con tubería embebida", parameter="Refuerzo normal a la tubería", classification="minimo_normativo", value=number_value(0.002, "As/Ac", "El refuerzo perpendicular a la tubería debe tener un área no menor de 0.002 veces el área de la sección de concreto."), standard="E.060", numeral="6.3.11", conditions=["La disposición debe coordinarse con el diseño y la geometría del elemento."], warning="No debe añadirse acero sin verificar recubrimiento, separación y anclaje.", faq_category="Acero de Refuerzo y Recubrimientos", question="¿La zona de una tubería embebida necesita refuerzo perpendicular?", answer="Sí. La E.060 exige un área no menor de 0.002 veces el área de la sección de concreto en dirección normal a la tubería.")
add(parameter_id="e060-tuberia-no-modifica-refuerzo", category="Instalaciones embebidas", element="Instalación de tuberías y ductos", parameter="Interferencia con el acero", classification="prohibicion", value=text_value("Las instalaciones deben ejecutarse sin cortar, doblar ni desplazar el refuerzo de su posición apropiada."), standard="E.060", numeral="6.3.12", conditions=["Los recorridos deben coordinarse antes del armado y vaciado."], warning="Mover barras para hacer pasar una tubería cambia el diseño estructural.", faq_category="Acero de Refuerzo y Recubrimientos", question="¿Se puede mover o cortar una barra para que pase una tubería?", answer="No. La E.060 exige instalar tuberías y ductos sin cortar, doblar ni desplazar el refuerzo.")
add(parameter_id="e060-junta-pisos-techos-tercio-central", category="Juntas de construcción", element="Junta en piso, losa o viga", parameter="Ubicación", classification="condicion_normativa", value=text_value("Las juntas de construcción en pisos y techos deben ubicarse dentro del tercio central del vano de losas, vigas y vigas principales."), standard="E.060", numeral="6.4.4", conditions=["La ubicación exacta debe estar definida en documentos y permitir transferencia de fuerzas."], warning="No debe confundirse con permiso para interrumpir cualquier elemento en cualquier punto del tercio central.", faq_category="Losas, Techos y Diafragmas", question="¿En qué zona se ubica una junta de construcción de una losa o viga?", answer="La E.060 la sitúa dentro del tercio central del vano, pero su posición exacta debe definirla el responsable estructural.")
add(parameter_id="e060-junta-viga-principal-desplazamiento-minimo", category="Juntas de construcción", element="Junta en viga principal", parameter="Distancia respecto a viga interceptante", classification="formula_normativa", value=formula_value("distancia ≥ 2b", "La junta debe desplazarse al menos dos veces el ancho de la viga que intercepta a la viga principal."), standard="E.060", numeral="6.4.5", conditions=["b es el ancho de la viga que intercepta."], warning="La regla no sustituye la definición de la junta en planos ni la transferencia de cortante.", faq_category="Vigas Soleras, Dinteles y Vanos", question="¿Qué distancia debe guardar una junta de viga principal respecto de una viga que la intercepta?", answer="Como mínimo dos veces el ancho de la viga que la intercepta.")
add(parameter_id="e060-vaciado-viga-losa-apoyo-endurecido", category="Juntas de construcción", element="Viga o losa apoyada en columna o muro", parameter="Espera antes del vaciado", classification="condicion_normativa", value=text_value("No debe vaciarse la viga o losa hasta que el concreto del apoyo vertical haya dejado de ser plástico."), standard="E.060", numeral="6.4.6", conditions=["Busca evitar fisuración por exudación y asentamiento plástico en la interfaz."], warning="No existe un tiempo único; debe verificarse la condición del concreto del apoyo.", faq_category="Concreto en Viviendas de Albañilería", question="¿Se puede vaciar inmediatamente la losa después de llenar columnas o muros?", answer="No debe hacerse mientras el concreto del apoyo vertical continúe plástico, salvo sistemas continuos respaldados por experiencia y aprobación.")

# E.060: ensayos y aceptación del concreto.
add(parameter_id="e060-ensayo-resistencia-frecuencia", category="Control de calidad del concreto", element="Muestreo de concreto", parameter="Frecuencia mínima", classification="condicion_normativa", value=text_value("Por cada clase de concreto: no menos de una muestra diaria, una por cada 50 m³, una por cada 300 m² de losa o muro y una por cada cinco camiones de premezclado; rige la condición más exigente."), standard="E.060", numeral="5.6.2.1", conditions=["Las frecuencias se aplican a cada clase de concreto colocada."], warning="Una obra pequeña no queda automáticamente exonerada del control.", faq_category="Compra de Materiales y Control de Calidad", question="¿Con qué frecuencia deben tomarse muestras para ensayos de resistencia?", answer="Como mínimo una por día, por cada 50 m³, por cada 300 m² de losa o muro y por cada cinco camiones de premezclado, aplicando la condición más exigente.")
add(parameter_id="e060-ensayo-resistencia-dos-probetas", category="Control de calidad del concreto", element="Ensayo de resistencia", parameter="Probetas por resultado", classification="minimo_normativo", value=number_value(2, "probetas cilíndricas", "Un ensayo de resistencia es el promedio de dos probetas de la misma muestra, ensayadas a los 28 días o a la edad especificada."), standard="E.060", numeral="5.6.2.3", conditions=["Las probetas deben fabricarse y curarse conforme a las normas de ensayo aplicables."], warning="Una sola probeta no constituye el ensayo definido por la E.060.", faq_category="Compra de Materiales y Control de Calidad", question="¿Cuántas probetas forman un ensayo de resistencia del concreto?", answer="Dos probetas cilíndricas de la misma muestra; el resultado es su promedio a los 28 días o a la edad especificada.")
add(parameter_id="e060-aceptacion-promedio-tres-ensayos", category="Control de calidad del concreto", element="Concreto ensayado", parameter="Promedio de resistencia", classification="formula_normativa", value=formula_value("promedio de 3 ensayos consecutivos ≥ f'c", "Cada promedio aritmético de tres ensayos consecutivos debe ser igual o superior a la resistencia especificada f'c."), standard="E.060", numeral="5.6.3.3(a)", conditions=["Debe cumplirse conjuntamente con el límite para resultados individuales."], warning="Un promedio aceptable no compensa automáticamente un resultado individual excesivamente bajo.", faq_category="Compra de Materiales y Control de Calidad", question="¿Qué promedio deben cumplir tres ensayos consecutivos de concreto?", answer="El promedio de tres ensayos consecutivos debe ser igual o mayor que f'c.")
add(parameter_id="e060-aceptacion-resultado-individual", category="Control de calidad del concreto", element="Resultado individual de resistencia", parameter="Reducción máxima respecto a f'c", classification="condicion_normativa", value=text_value("Si f'c ≤ 35 MPa, ningún resultado puede ser menor que f'c en más de 3.5 MPa; si f'c > 35 MPa, no puede ser menor en más de 0.1 f'c."), standard="E.060", numeral="5.6.3.3(b)", conditions=["El resultado individual es el promedio de dos cilindros."], warning="No debe evaluarse solo el promedio general de toda la obra.", faq_category="Compra de Materiales y Control de Calidad", question="¿Cuánto puede quedar por debajo de f'c un ensayo individual?", answer="Hasta 3.5 MPa cuando f'c es 35 MPa o menor; para resistencias mayores, hasta 10% de f'c.")
add(parameter_id="e060-curado-obra-relacion-minima-laboratorio", category="Control de calidad del concreto", element="Probetas curadas en obra", parameter="Relación con probetas de laboratorio", classification="minimo_normativo", value=number_value(85, "%", "Si la resistencia de probetas curadas en obra es inferior a 85% de las curadas en laboratorio, deben mejorarse protección y curado, salvo la excepción indicada por la norma."), standard="E.060", numeral="5.6.4.3", conditions=["La excepción aplica cuando las probetas de obra superan f'c en más de 3.5 MPa."], warning="Un resultado bajo puede revelar curado deficiente aunque la dosificación sea correcta.", faq_category="Compra de Materiales y Control de Calidad", question="¿Qué indica que las probetas curadas en obra alcancen menos del 85% de las de laboratorio?", answer="Que deben mejorarse los procedimientos de protección y curado, salvo la excepción prevista cuando la resistencia de obra supera ampliamente f'c.")
add(parameter_id="e060-testigos-cantidad-por-resultado-bajo", category="Control de calidad del concreto", element="Núcleos o testigos de concreto", parameter="Cantidad por resultado bajo", classification="minimo_normativo", value=number_value(3, "núcleos", "Deben extraerse tres núcleos por cada resultado de resistencia que esté por debajo del límite de aceptación cuando se confirma posible baja resistencia."), standard="E.060", numeral="5.6.5.2", conditions=["La extracción procede cuando los cálculos indican reducción significativa de capacidad y debe seguir ASTM C42M."], warning="La ubicación y extracción deben evitar dañar acero y requieren evaluación profesional.", faq_category="Compra de Materiales y Control de Calidad", question="¿Cuántos testigos se extraen por un resultado de concreto demasiado bajo?", answer="Tres núcleos por cada resultado bajo, cuando se confirma la posibilidad de concreto de baja resistencia y corresponde investigar la zona.")
add(parameter_id="e060-testigos-plazo-ensayo", category="Control de calidad del concreto", element="Núcleos extraídos", parameter="Plazo para ensayo", classification="condicion_normativa", value=text_value("Los núcleos deben ensayarse después de 48 horas y antes de siete días de extraídos, salvo plazo distinto aprobado por el profesional responsable."), standard="E.060", numeral="5.6.5.3", conditions=["Deben protegerse y almacenarse en recipientes o bolsas herméticas tras secar el agua superficial."], warning="Dejar testigos expuestos altera su humedad y el resultado.", faq_category="Compra de Materiales y Control de Calidad", question="¿Cuándo deben ensayarse los testigos extraídos del concreto?", answer="Después de 48 horas y antes de siete días, salvo que el profesional responsable apruebe otro plazo.")
add(parameter_id="e060-testigos-criterio-aceptacion", category="Control de calidad del concreto", element="Concreto evaluado con núcleos", parameter="Criterio de aceptación", classification="condicion_normativa", value=text_value("El promedio de tres núcleos debe ser al menos 85% de f'c y ningún núcleo menor de 75% de f'c."), standard="E.060", numeral="5.6.5.4", conditions=["Si los resultados son erráticos deben extraerse núcleos adicionales de la misma zona."], warning="Cumplir el promedio no basta si uno de los testigos queda por debajo del 75%.", faq_category="Compra de Materiales y Control de Calidad", question="¿Cuándo se considera adecuado el concreto evaluado mediante tres testigos?", answer="Cuando el promedio es al menos 85% de f'c y ninguno de los tres testigos es menor de 75% de f'c.")

# E.070: ejecución y control de albañilería.
add(parameter_id="e070-mano-obra-calificada-supervision", category="Ejecución de albañilería", element="Construcción de muros de albañilería", parameter="Mano de obra y supervisión", classification="condicion_normativa", value=text_value("La mano de obra debe ser calificada y debe supervisarse el cumplimiento de las exigencias constructivas."), standard="E.070", numeral="Artículo 10 (párrafo introductorio)", conditions=["La supervisión debe abarcar plomo, juntas, humedecimiento, aparejo y conexiones."], warning="La experiencia informal no sustituye el control de los requisitos del proyecto y la norma.", faq_category="Muros Portantes de Albañilería Confinada", question="¿La E.070 exige mano de obra calificada para levantar muros?", answer="Sí. El procedimiento de construcción exige mano de obra calificada y supervisión del cumplimiento de las reglas básicas.")
add(parameter_id="e070-muro-plomo-linea-proteccion", category="Ejecución de albañilería", element="Muro recién asentado", parameter="Plomo, alineación e integridad", classification="condicion_normativa", value=text_value("Los muros deben construirse a plomo y en línea, sin atentar contra su integridad mientras están recién asentados."), standard="E.070", numeral="10.1", conditions=["Debe evitarse golpear, cargar o desplazar el muro antes de que el mortero desarrolle estabilidad."], warning="Corregir el plomo empujando un paño alto puede romper las juntas.", faq_category="Muros Portantes de Albañilería Confinada", question="¿Se puede enderezar empujando un muro recién levantado?", answer="No debe atentarse contra su integridad. El muro debe construirse a plomo y en línea desde el asentado.")
add(parameter_id="e070-juntas-mortero-llenado-completo", category="Ejecución de albañilería", element="Juntas de muro asentado con mortero", parameter="Llenado", classification="condicion_normativa", value=text_value("Todas las juntas horizontales y verticales deben quedar completamente llenas de mortero."), standard="E.070", numeral="10.2", conditions=["Aplica a albañilería con unidades asentadas con mortero."], warning="Las juntas verticales vacías reducen resistencia, estanqueidad y comportamiento del muro.", faq_category="Morteros y Juntas de Albañilería", question="¿Es obligatorio llenar también las juntas verticales del muro?", answer="Sí. La E.070 exige que las juntas horizontales y verticales queden completamente llenas de mortero.")
add(parameter_id="e070-mortero-retemplado-una-vez", category="Ejecución de albañilería", element="Mortero de asentado", parameter="Retemplado", classification="maximo_normativo", value=number_value(1, "vez", "El agua evaporada puede reemplazarse una sola vez y antes de que venza el plazo de fragua inicial del cemento."), standard="E.070", numeral="10.3", conditions=["No se permite retemplar un mortero que ya inició su fragua."], warning="Agregar agua repetidamente altera la adherencia y la resistencia de las juntas.", faq_category="Morteros y Juntas de Albañilería", question="¿Cuántas veces se puede volver a agregar agua al mortero de asentado?", answer="Solo una vez para reponer agua evaporada y siempre antes de la fragua inicial del cemento.")
add(parameter_id="e070-unidad-limpia-sin-agua-libre", category="Ejecución de albañilería", element="Unidad antes del asentado", parameter="Estado superficial y colocación", classification="condicion_normativa", value=text_value("La unidad debe estar limpia de polvo y sin agua libre; debe asentarse presionando verticalmente, sin bambolearla."), standard="E.070", numeral="10.4", conditions=["El tratamiento de humedad depende del material de la unidad."], warning="Bambolear el ladrillo rompe la cama de mortero y deja juntas desuniformes.", faq_category="Ladrillos y Unidades de Albañilería", question="¿Cómo debe colocarse el ladrillo sobre el mortero?", answer="Con sus caras limpias y sin agua libre, presionándolo verticalmente y sin bambolearlo.")
add(parameter_id="e070-unidad-concreto-silicocalcarea-humedecimiento", category="Ejecución de albañilería", element="Unidad de concreto o sílico-calcárea", parameter="Humedecimiento previo", classification="condicion_normativa", value=text_value("Debe pasarse una brocha húmeda o rociarse las caras de asentado."), standard="E.070", numeral="10.4(a)", conditions=["No debe quedar agua libre sobre la superficie."], warning="Sumergir o saturar sin control no es el tratamiento indicado para estas unidades.", faq_category="Ladrillos y Unidades de Albañilería", question="¿Cómo se humedecen los bloques de concreto o unidades sílico-calcáreas antes de asentarlos?", answer="Se pasa una brocha húmeda o se rocían las caras de asentado, evitando agua libre.")
add(parameter_id="e070-unidad-arcilla-riego-previo", category="Ejecución de albañilería", element="Unidad de arcilla", parameter="Riego previo", classification="condicion_normativa", value=text_value("Según el clima, deben regarse durante media hora entre 10 y 15 horas antes del asentado."), standard="E.070", numeral="10.4(b)", conditions=["El objetivo es controlar la succión al momento de asentar."], warning="Mojar el ladrillo justo antes de colocarlo puede dejar agua libre o una succión inadecuada.", faq_category="Ladrillos y Unidades de Albañilería", question="¿Cuándo deben regarse los ladrillos de arcilla antes de asentarlos?", answer="Durante media hora, entre 10 y 15 horas antes, ajustando el tratamiento a las condiciones climáticas.")
add(parameter_id="e070-unidad-arcilla-succion-recomendada", category="Ejecución de albañilería", element="Unidad de arcilla al asentarse", parameter="Succión recomendada", classification="condicion_normativa", value=text_value("Se recomienda una succión entre 10 y 20 g/200 cm²-min al momento del asentado."), standard="E.070", numeral="10.4(b)", conditions=["Puede evaluarse aproximadamente mediante el método de campo descrito en la norma."], warning="Una unidad demasiado seca absorbe agua del mortero; una saturada perjudica la adherencia.", faq_category="Ladrillos y Unidades de Albañilería", question="¿Qué rango de succión recomienda la E.070 para un ladrillo de arcilla al asentarlo?", answer="Entre 10 y 20 g por 200 cm² por minuto.")
add(parameter_id="e070-primera-hilada-base-preparacion", category="Ejecución de albañilería", element="Base de la primera hilada", parameter="Preparación", classification="condicion_normativa", value=text_value("La superficie de concreto debe quedar rugosa, limpia de polvo y material suelto, y humedecida antes de asentar."), standard="E.070", numeral="10.5", conditions=["Aplica sobre losa o sobrecimiento según el caso."], warning="Asentar sobre una superficie lisa y polvorienta reduce la adherencia de la primera hilada.", faq_category="Muros Portantes de Albañilería Confinada", question="¿Cómo se prepara el sobrecimiento antes de asentar la primera hilada?", answer="Debe dejarse rugoso, limpiarse y humedecerse antes de colocar el mortero y las unidades.")
add(parameter_id="e070-junta-entre-jornadas-preparacion", category="Ejecución de albañilería", element="Junta de muro entre jornadas", parameter="Preparación", classification="condicion_normativa", value=text_value("La junta debe estar limpia de partículas sueltas y previamente humedecida."), standard="E.070", numeral="10.7", conditions=["Debe prepararse antes de continuar el asentado en la jornada siguiente."], warning="Continuar sobre mortero suelto o seco produce una unión débil.", faq_category="Morteros y Juntas de Albañilería", question="¿Cómo debe prepararse el muro antes de continuar el asentado al día siguiente?", answer="La junta entre jornadas debe limpiarse de partículas sueltas y humedecerse previamente.")
add(parameter_id="e070-aparejo-traslape-unidades", category="Ejecución de albañilería", element="Aparejo del muro", parameter="Traslape entre hiladas", classification="condicion_normativa", value=text_value("Las unidades deben traslaparse entre hiladas consecutivas mediante aparejo de soga, cabeza o amarre americano."), standard="E.070", numeral="10.8", conditions=["El aparejo debe corresponder al espesor y detalle del proyecto."], warning="Alinear juntas verticales continuas crea planos débiles.", faq_category="Muros Portantes de Albañilería Confinada", question="¿Pueden coincidir las juntas verticales en varias hiladas?", answer="No. La E.070 exige traslapar las unidades entre hiladas consecutivas mediante un aparejo permitido.")
add(parameter_id="e070-grout-ocupacion-total-sin-vibrar-barras", category="Ejecución de albañilería", element="Grout en celdas", parameter="Colocación y consolidación", classification="prohibicion", value=text_value("El grout debe ocupar totalmente las celdas y quedar sin cangrejeras; no se permite vibrar las varillas de refuerzo."), standard="E.070", numeral="10.9", conditions=["La consolidación debe realizarse con un procedimiento que no desplace ni haga vibrar el acero."], warning="Vibrar la barra no garantiza llenar la celda y puede perder adherencia o mover el refuerzo.", faq_category="Muros Portantes de Albañilería Confinada", question="¿Se puede vibrar la varilla para que baje el grout dentro del muro?", answer="No. Debe consolidarse el grout para llenar completamente las celdas, pero la E.070 prohíbe vibrar las varillas.")
add(parameter_id="e070-viga-peraltada-vaciado-con-losa", category="Ejecución de albañilería", element="Viga peraltada y losa de techo", parameter="Secuencia de vaciado", classification="condicion_normativa", value=text_value("Las vigas peraltadas deben vaciarse de una sola vez junto con la losa de techo."), standard="E.070", numeral="10.10", conditions=["El armado, encofrado y abastecimiento deben planificarse para mantener continuidad."], warning="Separar el vaciado sin junta diseñada puede comprometer la continuidad del conjunto.", faq_category="Vigas Soleras, Dinteles y Vanos", question="¿Una viga peraltada puede vaciarse separada de la losa de techo?", answer="La E.070 exige vaciar las vigas peraltadas de una sola vez conjuntamente con la losa.")
add(parameter_id="e070-instalacion-seca-diametro-maximo", category="Instalaciones en muros de albañilería", element="Tubo de instalación seca en muro", parameter="Diámetro máximo", classification="maximo_normativo", value=number_value(55, "mm", "Los tubos eléctricos, telefónicos u otras instalaciones secas solo pueden alojarse en muros cuando su diámetro máximo sea 55 mm."), standard="E.070", numeral="Artículo 2, instalaciones secas", conditions=["Deben colocarse en cavidades dejadas durante la construcción o en alvéolos y rellenarse según la norma."], warning="El límite no autoriza a picar el muro terminado.", faq_category="Instalaciones Eléctricas en Viviendas", question="¿Qué diámetro máximo puede tener un tubo eléctrico alojado en un muro de albañilería?", answer="55 mm, y debe colocarse en una cavidad prevista durante la construcción o en los alvéolos, nunca picando después.")
add(parameter_id="e070-instalacion-seca-recorrido-vertical-no-picado", category="Instalaciones en muros de albañilería", element="Instalación seca en muro", parameter="Recorrido y ejecución", classification="prohibicion", value=text_value("Los recorridos deben ser verticales y no se debe picar ni recortar el muro para alojar los tubos."), standard="E.070", numeral="Artículo 2, instalaciones secas", conditions=["Las cavidades deben preverse durante la construcción y luego rellenarse con concreto."], warning="Las ranuras horizontales cortan la sección resistente del muro portante.", faq_category="Instalaciones Eléctricas en Viviendas", question="¿Se puede picar horizontalmente un muro portante para meter tubos eléctricos?", answer="No. La E.070 exige recorridos verticales en cavidades previstas y prohíbe picar o recortar el muro.")
add(parameter_id="e070-instalacion-sanitaria-fuera-muro-portante", category="Instalaciones en muros de albañilería", element="Tubería sanitaria o mayor de 55 mm", parameter="Ubicación", classification="condicion_normativa", value=text_value("Debe recorrer fuera de los muros portantes, en falsas columnas, ductos especiales o muros no portantes."), standard="E.070", numeral="Artículo 2, instalaciones sanitarias", conditions=["La solución debe coordinarse en planos antes de construir."], warning="Empotrar desagües grandes dentro de un muro portante reduce gravemente su sección.", faq_category="Instalaciones Sanitarias en Viviendas", question="¿Dónde deben colocarse los desagües o tubos mayores de 55 mm?", answer="Fuera de los muros portantes, usando ductos, falsas columnas o muros no portantes previstos en el proyecto.")
add(parameter_id="e070-unidad-concreto-edad-minima", category="Control de calidad de albañilería", element="Unidad de albañilería de concreto curada con agua", parameter="Edad mínima de uso", classification="minimo_normativo", value=number_value(28, "días", "Las unidades de concreto curadas con agua deben tener al menos 28 días antes de utilizarse."), standard="E.070", numeral="5.1(d)", conditions=["También deben haber alcanzado resistencia especificada y estabilidad volumétrica."], warning="Usar bloques jóvenes puede causar contracción, fisuras y resistencia insuficiente.", faq_category="Ladrillos y Unidades de Albañilería", question="¿Cuántos días deben tener los bloques de concreto curados con agua antes de usarlos?", answer="Como mínimo 28 días, además de haber alcanzado resistencia y estabilidad volumétrica.")
add(parameter_id="e070-unidades-muestreo-lote", category="Control de calidad de albañilería", element="Lote de unidades de albañilería", parameter="Muestreo", classification="condicion_normativa", value=text_value("Por cada lote de hasta 50 millares se seleccionan 10 unidades: cinco para compresión y cinco para absorción, además de variación dimensional y alabeo."), standard="E.070", numeral="5.4(a)", conditions=["La selección debe efectuarse al azar a pie de obra."], warning="Escoger únicamente unidades visualmente buenas invalida la representatividad del control.", faq_category="Compra de Materiales y Control de Calidad", question="¿Cómo se muestrea un lote de ladrillos o bloques en obra?", answer="Por cada lote de hasta 50 000 unidades se toman al azar 10: cinco para compresión y cinco para absorción, además de los demás controles indicados.")
add(parameter_id="e070-unidades-dispersion-rechazo", category="Control de calidad de albañilería", element="Lote de unidades", parameter="Dispersión máxima antes de rechazo", classification="condicion_normativa", value=text_value("Si la dispersión supera 20% en unidades industriales o 40% en artesanales se ensaya otra muestra; si persiste, se rechaza el lote."), standard="E.070", numeral="5.5(a)", conditions=["La dispersión corresponde al coeficiente de variación de los resultados."], warning="Una resistencia promedio alta no compensa una producción excesivamente irregular.", faq_category="Compra de Materiales y Control de Calidad", question="¿Cuándo se rechaza un lote de ladrillos por resultados muy dispersos?", answer="Se repite la muestra si supera 20% en industriales o 40% en artesanales; si la dispersión persiste, se rechaza el lote.")
add(parameter_id="e070-unidades-absorcion-maxima", category="Control de calidad de albañilería", element="Unidad de albañilería", parameter="Absorción máxima", classification="condicion_normativa", value=text_value("Máximos: 22% para arcilla y sílico-calcárea, 12% para bloque de concreto P y 15% para bloque de concreto NP."), standard="E.070", numeral="5.5(b)", conditions=["La absorción debe determinarse mediante el ensayo correspondiente."], warning="No debe evaluarse únicamente por peso o apariencia de la unidad.", faq_category="Ladrillos y Unidades de Albañilería", question="¿Cuánta absorción máxima permite la E.070 en ladrillos y bloques?", answer="22% para arcilla y sílico-calcárea, 12% para bloque de concreto P y 15% para bloque NP.")
add(parameter_id="e070-mortero-arena-mar-prohibida", category="Materiales de albañilería", element="Arena para mortero", parameter="Procedencia", classification="prohibicion", value=text_value("No debe emplearse arena de mar en el mortero de albañilería."), standard="E.070", numeral="6.2(b)", conditions=["La arena debe ser gruesa natural, libre de materia orgánica y sales y cumplir la granulometría aplicable."], warning="El lavado informal no garantiza eliminar sales ni obtener granulometría adecuada.", faq_category="Morteros y Juntas de Albañilería", question="¿Se puede usar arena de mar para preparar mortero?", answer="No. La E.070 prohíbe expresamente emplear arena de mar.")
add(parameter_id="e070-grout-tipo-segun-alveolo", category="Materiales de albañilería", element="Grout para muro armado", parameter="Tipo según dimensión del alvéolo", classification="condicion_normativa", value=text_value("Se usa grout fino cuando la dimensión menor del alvéolo es inferior a 60 mm y grout grueso cuando es igual o mayor a 60 mm."), standard="E.070", numeral="7.2", conditions=["La granulometría y composición deben cumplir los requisitos del artículo 7."], warning="Usar agregado grueso en una celda pequeña impide el llenado y genera cangrejeras.", faq_category="Morteros y Juntas de Albañilería", question="¿Cuándo corresponde usar grout fino o grueso?", answer="Fino si la dimensión menor del alvéolo es menor de 60 mm; grueso si es igual o mayor de 60 mm.")
add(parameter_id="e070-grout-revenimiento", category="Materiales de albañilería", element="Concreto líquido o grout", parameter="Revenimiento", classification="condicion_normativa", value=text_value("El revenimiento debe estar entre 225 y 275 mm, medido con el cono de Abrams."), standard="E.070", numeral="7.4", conditions=["La mezcla debe ser uniforme y sin segregación y batirse mecánicamente."], warning="Lograr fluidez agregando agua sin dosificación reduce resistencia y puede separar los agregados.", faq_category="Morteros y Juntas de Albañilería", question="¿Qué revenimiento debe tener el grout de albañilería?", answer="Entre 225 y 275 mm en el cono de Abrams, manteniendo una mezcla uniforme y sin segregación.")

# G.050: organización, electricidad provisional, altura, andamios y demolición.
add(parameter_id="g050-via-circulacion-ancho-minimo", category="Seguridad durante la construcción", element="Vía peatonal o de acarreo manual", parameter="Ancho mínimo", classification="minimo_normativo", value=number_value(0.60, "m", "El ancho mínimo de las vías para circulación de personas o acarreo manual es 0.60 m."), standard="G.050", numeral="7.4", conditions=["El ancho final debe aumentar según número de usuarios y actividad."], warning="El mínimo no permite obstrucciones, materiales, cables o salientes dentro de la ruta.", faq_category="Seguridad en la Autoconstrucción", question="¿Cuál es el ancho mínimo de una vía peatonal dentro de la obra?", answer="0.60 m como mínimo, y puede requerirse más según la cantidad de personas y el tipo de trabajo.")
add(parameter_id="g050-electricidad-provisional-persona-competente", category="Seguridad durante la construcción", element="Instalación eléctrica provisional", parameter="Responsable de ejecución y mantenimiento", classification="condicion_normativa", value=text_value("Debe ser realizada y mantenida por una persona con competencia acreditada."), standard="G.050", numeral="7.3", conditions=["La instalación debe cumplir la normativa eléctrica vigente y proteger a trabajadores y terceros."], warning="Las conexiones provisionales improvisadas son causa de electrocución e incendio.", faq_category="Seguridad en la Autoconstrucción", question="¿Quién debe instalar y mantener la electricidad provisional de una obra?", answer="Una persona con competencia acreditada; no debe improvisarse mediante empalmes domésticos o cables expuestos.")
add(parameter_id="g050-tablero-diferenciales-sensibilidad", category="Seguridad durante la construcción", element="Tablero eléctrico provisional", parameter="Interruptores diferenciales", classification="condicion_normativa", value=text_value("Debe contar con diferenciales de alta sensibilidad de 30 mA y baja sensibilidad de 300 mA."), standard="G.050", numeral="7.3", conditions=["También debe contar con interruptores termomagnéticos, puerta, llave y puesta a tierra."], warning="Un interruptor termomagnético por sí solo no reemplaza la protección diferencial.", faq_category="Seguridad en la Autoconstrucción", question="¿Qué sensibilidad deben tener los diferenciales de un tablero provisional de obra?", answer="La G.050 exige diferenciales de 30 mA y 300 mA, además de las demás protecciones del tablero.")
add(parameter_id="g050-electricidad-provisional-puesta-tierra", category="Seguridad durante la construcción", element="Circuitos eléctricos provisionales", parameter="Puesta a tierra", classification="condicion_normativa", value=text_value("Todos los circuitos eléctricos provisionales deben contar con línea de tierra conectada a un pozo adecuado a la obra."), standard="G.050", numeral="7.3", conditions=["Debe cumplirse el Código Nacional de Electricidad."], warning="Clavar una varilla sin diseño ni medición no demuestra una puesta a tierra eficaz.", faq_category="Seguridad en la Autoconstrucción", question="¿Todos los circuitos provisionales de obra necesitan puesta a tierra?", answer="Sí. La G.050 exige línea de tierra en todos los circuitos y descarga en un pozo acorde con la obra.")
add(parameter_id="g050-extension-electrica-calibre-minimo", category="Seguridad durante la construcción", element="Extensión eléctrica temporal", parameter="Conductor mínimo", classification="minimo_normativo", value=text_value("Debe utilizar conductor tripolar vulcanizado flexible de calibre adecuado, como mínimo NMT 3x10, en toda su longitud."), standard="G.050", numeral="7.3", conditions=["Los enchufes y tomacorrientes deben ser industriales, blindados y sellados."], warning="Los cables mellizos domésticos no son adecuados para golpes, humedad y tránsito de obra.", faq_category="Seguridad en la Autoconstrucción", question="¿Qué tipo mínimo de cable exige la G.050 para una extensión temporal?", answer="Conductor tripolar vulcanizado flexible, como mínimo NMT 3x10, con conexiones industriales adecuadas.")
add(parameter_id="g050-extension-electrica-empalme-maximo", category="Seguridad durante la construcción", element="Extensión eléctrica temporal", parameter="Frecuencia de empalmes", classification="maximo_normativo", value=number_value(1, "empalme por 50 m", "Se acepta como máximo un empalme cada 50 m, con conductores del mismo calibre y conectores protegidos."), standard="G.050", numeral="7.3", conditions=["El empalme debe utilizar conectores adecuados, cinta vulcanizante y aislante."], warning="Unir cables solo retorciéndolos y cubriéndolos con cinta común no cumple la exigencia.", faq_category="Seguridad en la Autoconstrucción", question="¿Cuántos empalmes se permiten en una extensión eléctrica temporal?", answer="Como máximo uno cada 50 m, usando conductores del mismo calibre y conectores correctamente aislados.")
add(parameter_id="g050-obra-menos-25-supervisor-prevencion", category="Seguridad durante la construcción", element="Obra con menos de 25 trabajadores", parameter="Representación preventiva", classification="condicion_normativa", value=text_value("Debe designarse un Supervisor de prevención de riesgos elegido entre trabajadores de nivel técnico superior con experiencia certificada."), standard="G.050", numeral="8.1", conditions=["Representa a los trabajadores en seguridad y salud durante la obra."], warning="Que la obra sea pequeña no elimina la organización preventiva.", faq_category="Seguridad en la Autoconstrucción", question="¿Qué organización de seguridad corresponde a una obra con menos de 25 trabajadores?", answer="Debe designarse un Supervisor de prevención de riesgos elegido por los trabajadores entre personal técnico con experiencia certificada.")
add(parameter_id="g050-obra-25-comite-seguridad", category="Seguridad durante la construcción", element="Obra con 25 o más trabajadores", parameter="Comité de seguridad", classification="condicion_normativa", value=text_value("Debe constituirse un Comité Técnico de Seguridad y Salud en el Trabajo."), standard="G.050", numeral="8.2", conditions=["Lo integran residente, jefe de prevención y dos representantes de trabajadores, además de invitados sin voto."], warning="Nombrar informalmente a una persona no reemplaza el comité exigido para esta dotación.", faq_category="Seguridad en la Autoconstrucción", question="¿Desde cuántos trabajadores debe existir un comité técnico de seguridad en obra?", answer="Desde 25 trabajadores. Con 25 o más debe constituirse el CTSST con la integración indicada por la G.050.")
add(parameter_id="g050-comite-reunion-maximo", category="Seguridad durante la construcción", element="Comité Técnico de Seguridad y Salud", parameter="Frecuencia de reunión", classification="maximo_normativo", value=number_value(30, "días", "El comité debe reunirse cada 30 días como máximo; puede acordar una frecuencia menor."), standard="G.050", numeral="8.5", conditions=["Las ocurrencias y acuerdos deben registrarse en actas oficiales."], warning="El comité no debe existir solo en documentos sin reuniones ni seguimiento.", faq_category="Seguridad en la Autoconstrucción", question="¿Cada cuánto debe reunirse el comité de seguridad de una obra?", answer="Cada 30 días como máximo, pudiendo reunirse con mayor frecuencia según las características de la obra.")
add(parameter_id="g050-plan-seguridad-obligatorio", category="Seguridad durante la construcción", element="Toda obra de construcción", parameter="Plan de Seguridad y Salud", classification="condicion_normativa", value=text_value("Toda obra debe contar con un Plan de Seguridad y Salud en el Trabajo antes del inicio de las actividades."), standard="G.050", numeral="9", conditions=["Debe abarcar riesgos, protecciones colectivas, trabajos de alto riesgo, capacitación, inspecciones y emergencias."], warning="Un listado genérico de EPP no sustituye un plan adaptado a los trabajos reales.", faq_category="Seguridad en la Autoconstrucción", question="¿Una vivienda pequeña necesita Plan de Seguridad y Salud en el Trabajo?", answer="Sí. La G.050 indica que toda obra de construcción debe contar con un PSST implementado antes de iniciar los trabajos.")
add(parameter_id="g050-plan-seguridad-partida-presupuesto", category="Seguridad durante la construcción", element="Presupuesto de obra", parameter="Partida de seguridad", classification="condicion_normativa", value=text_value("El presupuesto debe incluir una partida específica denominada Plan de Seguridad y Salud en el Trabajo."), standard="G.050", numeral="9", conditions=["Debe estimar el costo de los mecanismos técnicos y administrativos del plan."], warning="La seguridad no debe financiarse únicamente con sobrantes o compras improvisadas.", faq_category="Licencias, Planos y Responsables", question="¿El presupuesto de obra debe incluir una partida específica de seguridad?", answer="Sí. La G.050 exige una partida denominada Plan de Seguridad y Salud en el Trabajo.")
add(parameter_id="g050-caida-altura-arnes-umbral", category="Seguridad durante la construcción", element="Trabajo con caída libre", parameter="Altura para sistema de detención", classification="minimo_normativo", value=number_value(1.80, "m", "Se requiere sistema de detención de caídas cuando la altura de caída libre sea mayor de 1.80 m."), standard="G.050", numeral="20.1", conditions=["También se exige a menor altura en bordes, superficies inclinadas o sobre peligros especiales."], warning="El umbral no significa que por debajo de 1.80 m toda situación sea segura.", faq_category="Seguridad en la Autoconstrucción", question="¿Desde qué altura se exige arnés y sistema de detención de caídas?", answer="Cuando la caída libre puede ser mayor de 1.80 m, además de otros supuestos de riesgo que se aplican incluso a menor altura.")
add(parameter_id="g050-caida-cercania-borde", category="Seguridad durante la construcción", element="Trabajo cerca de borde sin baranda", parameter="Distancia de protección", classification="minimo_normativo", value=number_value(1.80, "m", "Se requiere sistema de detención al trabajar a menos de 1.80 m del borde de techos, losas, aberturas o excavaciones sin baranda."), standard="G.050", numeral="20.1", conditions=["La medida se aplica aunque la persona no esté exactamente sobre el borde."], warning="Confiar en mantener el equilibrio no constituye protección contra caída.", faq_category="Seguridad en la Autoconstrucción", question="¿Necesito arnés si trabajo cerca del borde de una losa sin baranda?", answer="Sí, cuando se trabaja a menos de 1.80 m del borde, abertura o excavación sin protección perimetral.")
add(parameter_id="g050-caida-anclaje-resistencia-minima", category="Seguridad durante la construcción", element="Punto de anclaje de sistema anticaídas", parameter="Resistencia mínima", classification="minimo_normativo", value=number_value(2265, "kgf", "El punto de anclaje debe resistir como mínimo 2265 kgf."), standard="G.050", numeral="20.1", conditions=["Debe ubicarse sobre la cabeza cuando corresponda e instalarse por persona competente."], warning="No debe anclarse el arnés a barandas, tuberías o elementos cuya resistencia no esté comprobada.", faq_category="Seguridad en la Autoconstrucción", question="¿Qué resistencia mínima debe tener un punto de anclaje para arnés?", answer="Como mínimo 2265 kgf, y debe ser seleccionado e instalado por una persona competente.")
add(parameter_id="g050-caida-libre-distancia-maxima", category="Seguridad durante la construcción", element="Sistema de detención de caídas", parameter="Caída libre máxima de diseño", classification="maximo_normativo", value=number_value(1.80, "m", "La altura del enganche debe calcularse para que la caída libre máxima sea 1.80 m."), standard="G.050", numeral="20.1", conditions=["Debe considerarse elongación de línea de vida y obstáculos inferiores."], warning="Un anclaje demasiado bajo puede hacer que el trabajador golpee el nivel inferior antes de detenerse.", faq_category="Seguridad en la Autoconstrucción", question="¿Cuál es la caída libre máxima que debe considerarse al ubicar el anclaje?", answer="1.80 m como máximo, considerando además elongación del sistema y obstáculos cercanos.")
add(parameter_id="g050-andamio-distancia-electricidad", category="Seguridad durante la construcción", element="Andamio próximo a sistema eléctrico", parameter="Distancia mínima", classification="condicion_normativa", value=text_value("Distancia mínima: 0.90 m para sistemas de hasta 300 V y 3.00 m para sistemas de más de 300 V."), standard="G.050", numeral="21.4", conditions=["Ninguna parte del andamio o del cuerpo del trabajador debe invadir la distancia."], warning="La distancia puede requerir medidas adicionales o desenergización según el riesgo.", faq_category="Seguridad en la Autoconstrucción", question="¿Qué distancia debe guardar un andamio de una línea eléctrica?", answer="Al menos 0.90 m hasta 300 V y 3.00 m por encima de 300 V, evitando todo contacto del andamio o del trabajador.")
add(parameter_id="g050-andamio-movimiento-sin-personas", category="Seguridad durante la construcción", element="Andamio móvil", parameter="Movimiento", classification="prohibicion", value=text_value("Se prohíbe que los trabajadores permanezcan sobre el andamio mientras se mueve."), standard="G.050", numeral="21.4", conditions=["Las garruchas deben mantenerse frenadas cuando haya personas trabajando."], warning="Moverlo con personas encima puede causar vuelco, caída o atrapamiento.", faq_category="Seguridad en la Autoconstrucción", question="¿Se puede mover un andamio con una persona todavía encima?", answer="No. La G.050 lo prohíbe expresamente.")
add(parameter_id="g050-andamio-inspeccion-diaria", category="Seguridad durante la construcción", element="Andamio o plataforma", parameter="Inspección", classification="condicion_normativa", value=text_value("Debe inspeccionarse diariamente antes de usarlo y conservar la tarjeta de control correspondiente."), standard="G.050", numeral="21.4 y 21.6", conditions=["Debe revisarse nuevamente después de cambios, daños o condiciones que afecten su estabilidad."], warning="Una inspección realizada al momento del armado no cubre aflojamientos o modificaciones posteriores.", faq_category="Seguridad en la Autoconstrucción", question="¿Cada cuánto debe revisarse un andamio en uso?", answer="Diariamente antes de usarlo, además de las revisiones periódicas por personal competente y tras cualquier cambio o daño.")
add(parameter_id="g050-demolicion-cerco-altura-minima", category="Seguridad durante la construcción", element="Área de demolición", parameter="Altura del cerco de protección", classification="minimo_normativo", value=number_value(2.40, "m", "Para proteger al público debe levantarse un cerco de 2.40 m de alto alrededor del área de demolición."), standard="G.050", numeral="25.3.1", conditions=["Las puertas deben permanecer cerradas fuera de las horas de trabajo."], warning="Una cinta de peligro no reemplaza el cerco cuando existe exposición del público.", faq_category="Remodelaciones y Demoliciones", question="¿Qué altura mínima debe tener el cerco alrededor de una demolición?", answer="2.40 m para proteger al público, con los accesos cerrados fuera de las horas de trabajo.")
add(parameter_id="g050-demolicion-plataforma-proteccion", category="Seguridad durante la construcción", element="Plataforma exterior contra caída de materiales", parameter="Carga y ancho", classification="condicion_normativa", value=text_value("Debe soportar una carga dinámica de 600 kg/m² y tener un ancho exterior mínimo de 1.50 m."), standard="G.050", numeral="25.3.1", conditions=["Se instala cuando sea necesaria para proteger contra caída de materiales durante demolición."], warning="Debe diseñarse y apoyarse para la carga dinámica; no basta una tabla ligera.", faq_category="Remodelaciones y Demoliciones", question="¿Qué capacidad y ancho requiere una plataforma de protección en demolición?", answer="Debe soportar 600 kg/m² de carga dinámica y tener por lo menos 1.50 m de ancho exterior.")
add(parameter_id="g050-orden-limpieza-rutas-libres", category="Seguridad durante la construcción", element="Áreas y rutas de obra", parameter="Orden y limpieza", classification="condicion_normativa", value=text_value("Áreas de trabajo, circulación, evacuación y zonas seguras deben mantenerse limpias y libres de obstáculos; los clavos deben retirarse de la madera."), standard="G.050", numeral="15", conditions=["Cables, mangueras, materiales y sobrantes no deben bloquear rutas."], warning="El desorden puede impedir una evacuación y causar tropiezos, pinchazos e incendios.", faq_category="Seguridad en la Autoconstrucción", question="¿Qué exige la G.050 sobre orden y limpieza en obra?", answer="Mantener áreas de trabajo y rutas limpias y libres, retirar clavos y devolver sobrantes al almacén al finalizar la jornada.")
add(parameter_id="g050-residuos-segregacion", category="Seguridad durante la construcción", element="Residuos de obra", parameter="Segregación", classification="condicion_normativa", value=text_value("Toda obra debe separar residuos peligrosos de los no peligrosos y almacenarlos temporalmente en áreas o recipientes identificados."), standard="G.050", numeral="16", conditions=["Los peligrosos deben permanecer en áreas aisladas y señalizadas hasta su disposición especializada."], warning="Mezclar solventes, aceites, envases y escombros impide un manejo seguro.", faq_category="Seguridad en la Autoconstrucción", question="¿Deben separarse los residuos peligrosos del desmonte común?", answer="Sí. La G.050 exige segregarlos, identificarlos y mantener los peligrosos en áreas aisladas hasta su disposición adecuada.")

# GE.030: gestión y evidencia de calidad.
add(parameter_id="ge030-proyecto-listas-controles-ensayos", category="Gestión de calidad", element="Proyecto de construcción", parameter="Documentación de control", classification="condicion_normativa", value=text_value("El proyecto debe indicar listas de verificación, controles, ensayos y pruebas que se ejecuten paralelamente a los procesos constructivos."), standard="GE.030", numeral="Artículo 1", conditions=["Debe definir puntos de control y criterios de aceptación."], warning="Inspeccionar solo al final no detecta trabajos ocultos ni permite corregir a tiempo.", faq_category="Licencias, Planos y Responsables", question="¿El proyecto debe indicar qué controles y ensayos se harán durante la obra?", answer="Sí. GE.030 exige listas de verificación, controles, ensayos y pruebas paralelos a los procesos constructivos.")
add(parameter_id="ge030-construccion-profesional-colegiado", category="Gestión de calidad", element="Ejecución de la construcción", parameter="Responsabilidad profesional", classification="condicion_normativa", value=text_value("La construcción debe ejecutarse bajo responsabilidad de un profesional colegiado."), standard="GE.030", numeral="Artículo 5(a)", conditions=["La responsabilidad debe corresponder al alcance y especialidad del proyecto."], warning="La autoconstrucción no elimina la necesidad de dirección y responsabilidad profesional.", faq_category="Licencias, Planos y Responsables", question="¿Una obra de vivienda debe ejecutarse bajo responsabilidad de un profesional colegiado?", answer="Sí. GE.030 establece este criterio de calidad para la ejecución de la construcción.")
add(parameter_id="ge030-constructor-evidencias-calidad", category="Gestión de calidad", element="Constructor", parameter="Evidencias de cumplimiento", classification="condicion_normativa", value=text_value("Debe entregar evidencias de cumplimiento de códigos, reglamentos y normas, junto con pruebas, ensayos, análisis e investigaciones previstas."), standard="GE.030", numeral="Artículo 9", conditions=["Las evidencias deben relacionarse con los elementos y procesos ejecutados."], warning="Fotografías generales no sustituyen certificados, protocolos y resultados identificados.", faq_category="Compra de Materiales y Control de Calidad", question="¿Qué evidencias de calidad debe conservar y entregar el constructor?", answer="Resultados de pruebas y ensayos, análisis, investigaciones de campo y documentos que demuestren cumplimiento de normas y proyecto.")
add(parameter_id="ge030-supervisor-exige-calidad", category="Gestión de calidad", element="Supervisor de obra", parameter="Responsabilidad de calidad", classification="condicion_normativa", value=text_value("El supervisor debe exigir la aplicación de la gestión de calidad y requerir aclaraciones sobre aspectos ambiguos o no definidos."), standard="GE.030", numeral="Artículo 10", conditions=["Su actuación debe ser preventiva y orientada a alcance, plazo, calidad y costo."], warning="Autorizar verbalmente una modificación ambigua sin consulta deja la obra sin trazabilidad.", faq_category="Licencias, Planos y Responsables", question="¿Qué debe hacer el supervisor cuando un plano es ambiguo o incompleto?", answer="Debe requerir las aclaraciones o consultas necesarias y exigir la gestión de calidad de forma preventiva.")
add(parameter_id="ge030-plan-aseguramiento-cada-etapa", category="Gestión de calidad", element="Cada etapa del proyecto", parameter="Plan de aseguramiento de calidad", classification="condicion_normativa", value=text_value("Cada etapa debe contar con un plan para planificar, ejecutar y controlar, incluyendo acciones correctivas o preventivas."), standard="GE.030", numeral="Artículo 15", conditions=["El plan debe incluir procedimientos, registros u otros documentos de control."], warning="Corregir defectos después de cubrirlos suele ser más costoso o imposible.", faq_category="Compra de Materiales y Control de Calidad", question="¿Cada etapa de la obra necesita un plan de aseguramiento de calidad?", answer="Sí. Debe planificarse lo que se ejecutará, hacerlo según lo previsto y controlar resultados y correcciones.")
add(parameter_id="ge030-expediente-final-etapa", category="Gestión de calidad", element="Etapa concluida del proyecto", parameter="Expediente final", classification="condicion_normativa", value=text_value("Al finalizar cada etapa debe organizarse un expediente que demuestre el cumplimiento del plan de calidad y entregarse al cliente."), standard="GE.030", numeral="Artículo 17", conditions=["Debe conservar información necesaria para mantenimiento, remodelación y operación."], warning="Sin expediente se pierden ubicaciones de instalaciones, pruebas, cambios y criterios de aceptación.", faq_category="Licencias, Planos y Responsables", question="¿Qué documentación debe organizarse al terminar una etapa de construcción?", answer="Un expediente final que demuestre el cumplimiento del plan de calidad y sirva para mantenimiento, remodelación y operación futura.")

if len(new_parameters) != 92:
    raise SystemExit(f"Se esperaban 92 parámetros nuevos y se generaron {len(new_parameters)}.")
if next_question != 1662:
    raise SystemExit(f"La numeración final esperada era q1661; siguiente={next_question}.")

for faq_category, question_item in new_questions:
    category_map[faq_category].setdefault("preguntas", []).append(question_item)

norm["parametros"].extend(new_parameters)
norm["version"] = "1.5.0"
norm["fecha_revision"] = REVIEW_DATE

question_total = sum(
    len([item for item in category.get("preguntas", []) if isinstance(item, dict)])
    for category in faq.get("categorias", [])
)
if len(norm["parametros"]) != 192:
    raise SystemExit(f"Se esperaban 192 parámetros y hay {len(norm['parametros'])}.")
if question_total != 1661:
    raise SystemExit(f"Se esperaban 1661 preguntas y hay {question_total}.")

for key in ("total_preguntas", "cantidad_preguntas", "total"):
    if isinstance(faq.get(key), int):
        faq[key] = question_total
if isinstance(faq.get("metadata"), dict):
    for key in ("total_preguntas", "cantidad_preguntas", "total"):
        if isinstance(faq["metadata"].get(key), int):
            faq["metadata"][key] = question_total
    if "fecha_revision" in faq["metadata"]:
        faq["metadata"]["fecha_revision"] = REVIEW_DATE

NORM_PATH.write_text(json.dumps(norm, ensure_ascii=False, separators=(",", ":")) + "\n", encoding="utf-8")
FAQ_PATH.write_text(json.dumps(faq, ensure_ascii=False, separators=(",", ":")) + "\n", encoding="utf-8")

check = CHECK_PATH.read_text(encoding="utf-8")
replacements = [
    ("if len(base.parametros) < 100:", "if len(base.parametros) < 192:"),
    ("por lo menos 100 parámetros validados", "por lo menos 192 parámetros validados"),
    ("if validados < 99:", "if validados < 191:"),
    ("al menos 99 numerales validados", "al menos 191 numerales validados"),
    ('if base.version != "1.4.0":', 'if base.version != "1.5.0":'),
    ("La versión normativa esperada es 1.4.0", "La versión normativa esperada es 1.5.0"),
    ("if len(todas) < 1569:", "if len(todas) < 1661:"),
    ("El lote 4 requiere por lo menos 1569 preguntas técnicas.", "El bloque de procesos requiere por lo menos 1661 preguntas técnicas."),
]
for old, new in replacements:
    if old not in check:
        raise SystemExit(f"No se encontró en el validador: {old}")
    check = check.replace(old, new, 1)

marker = '    detalle = api.detalle_parametro_normativo(\n        "a010-escalera-contrahuella-maxima"\n    )\n'
if marker not in check:
    raise SystemExit("No se encontró el punto de inserción de pruebas.")
extra = '''    mezclado = api.detalle_parametro_normativo(\n        "e060-mezclado-tiempo-minimo"\n    )\n    if mezclado["valor"]["valor"] != 90:\n        raise SystemExit("El tiempo mínimo de mezclado debe conservar 90 segundos.")\n\n    tubo_columna = api.detalle_parametro_normativo(\n        "e060-columna-tuberias-area-maxima"\n    )\n    if tubo_columna["valor"]["valor"] != 4:\n        raise SystemExit("Las tuberías en columna deben conservar el límite de 4%.")\n\n    caida = api.detalle_parametro_normativo(\n        "g050-caida-anclaje-resistencia-minima"\n    )\n    if caida["valor"]["valor"] != 2265:\n        raise SystemExit("El anclaje anticaídas debe conservar 2265 kgf.")\n\n    unidades = api.detalle_parametro_normativo(\n        "e070-unidad-concreto-edad-minima"\n    )\n    if unidades["valor"]["valor"] != 28:\n        raise SystemExit("Las unidades de concreto deben conservar 28 días mínimos.")\n\n'''
check = check.replace(marker, extra + marker, 1)
CHECK_PATH.write_text(check, encoding="utf-8")

DOC_PATH.write_text(
    """# Validación normativa de procesos constructivos, control y seguridad — 27 de julio de 2026

## Alcance

Se incorporaron 92 parámetros y 92 preguntas sobre:

- medición, mezclado, transporte, colocación y consolidación del concreto;
- clima, encofrado, desencofrado, puntales y reapuntalamiento;
- tuberías y ductos embebidos y juntas de construcción;
- muestreo, probetas, aceptación y testigos de concreto;
- tratamiento de unidades, mortero, grout, aparejo e instalaciones en muros;
- electricidad provisional, organización preventiva, trabajo en altura, andamios y demolición;
- planificación, evidencia y expedientes de calidad.

## Fuentes oficiales revisadas

- E.060 Concreto Armado — DS N.° 010-2009-VIVIENDA.
- E.070 Albañilería — RNE aprobado mediante DS N.° 011-2006-VIVIENDA.
- G.050 Seguridad durante la Construcción — DS N.° 010-2009-VIVIENDA.
- GE.030 Calidad de la Construcción — RNE aprobado mediante DS N.° 011-2006-VIVIENDA.

## Resultado

- Versión normativa: `1.5.0`.
- Parámetros totales: 192.
- Registros validados con numeral: 191.
- Registros piloto: 1.
- Preguntas técnicas: 1661.

## Criterios editoriales

- Los procedimientos sin medida única se presentan como condiciones y no como cifras inventadas.
- Los requisitos de seguridad se mantienen con su supuesto de aplicación y no como sustitutos del PSST.
- Los límites de tuberías embebidas no autorizan a cortar o desplazar acero.
- Las reglas de aceptación del concreto se separan en frecuencia, probetas, promedios y testigos.
- Las instrucciones de albañilería distinguen material, humedecimiento, asentado, grout e instalaciones.
- La gestión de calidad exige evidencia durante la ejecución, no únicamente una inspección final.
""",
    encoding="utf-8",
)

print(
    f"Aplicados {len(new_parameters)} parámetros, {len(new_questions)} preguntas; "
    f"totales: {len(norm['parametros'])} y {question_total}."
)
